apiVersion: v1
kind: Service
metadata:
  labels:
    app: todos-mongoui
  name: todos-mongoui-external
  namespace: mongodb
spec:
  ports:
    - nodePort: 32000
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: todos-mongoui
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: todos-mongoui
  namespace: mongodb
  labels:
    app: todos-mongoui
spec:
  containers:
    - name: todos-mongoui-container
      image: corbsmartin/todos-mongoui:1.0.0.SNAP
      imagePullPolicy: Always
      env:
        - name: TODOS_WEBUI_PLACEHOLDER
          value: "Milk, Bread, MongoDB?"
        - name: SPRING_DATA_MONGODB_URI
          value: "mongodb://kube15.retro.io:30188/todosdb?retryWrites=true"