spring:
  application:
    name: 'todos-mongoui'
  thymeleaf:
    cache: false
  security:
    user:
      name: 'Mongo User'
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      host: mongodb1.retro.io
      port: 27017
      database: todosdb
      authentication-database: admin
      username: corbs
      password: changeme
todos:
  webui:
    placeholder: "Talk Next Steps?"
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    io.todos: TRACE

