spring:
  application:
    name: 'todos-mongoui'
  thymeleaf:
    cache: false
  security:
    user:
      name: 'Mongo User'
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: 'mongodb://localhost:27017/todosdb?retryWrite=true'
todos:
  webui:
    placeholder: "Walk the Dog?"
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    io.todos: TRACE
    org.springframework: OFF
